name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.sh
        run: bash checkout.sh

      - uses: nanasess/setup-chromedriver@master
      - run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

      - name: run buildRun.sh
        run: sh buildRun.sh
