name: CI Linux
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.sh
        run: bash checkout.sh

      - name: run buildRun.sh
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: sh buildRun.sh

      - name: Send mail on failure
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: GitHub Action 'CI Linux' on devonfw-tutorials/tutorial-compiler has failed
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} finished with status ${{ job.status }}. Please check the logs!
          to: todo
          from: devonfw-tutorials/tutorial-compiler
