name: CI Windows Test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: 	windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install Pandoc
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install pandoc

      - name: install Ruby
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install ruby

      - name: install AsciiDoctor
        run: gem install asciidoctor
        
      - name: test asciidoctor
        run: asciidoctor -v
        
      - name: test pandoc
        run: pandoc -v
