name: CI Windows
on:
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: 	windows-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2-beta
        
      - name: install TS
        run: npm install typescript
      
      - name: npm install
        run: npm install

      - name: run checkout.ps1
        run: .\checkout.ps1

      - name: run buildRun.ps1 --user ${{ github.actor }} --branch ${{github.ref}}
        run: .\buildRun.ps1 --user ${{ github.actor }} --branch ${GITHUB_REF##*/}
